// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("fsfbl")>]
[<assembly: AssemblyProductAttribute("fsfbl")>]
[<assembly: AssemblyDescriptionAttribute("Fantasy baseball analysis in F#")>]
[<assembly: AssemblyVersionAttribute("1.0")>]
[<assembly: AssemblyFileVersionAttribute("1.0")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "fsfbl"
    let [<Literal>] AssemblyProduct = "fsfbl"
    let [<Literal>] AssemblyDescription = "Fantasy baseball analysis in F#"
    let [<Literal>] AssemblyVersion = "1.0"
    let [<Literal>] AssemblyFileVersion = "1.0"
    let [<Literal>] AssemblyConfiguration = "Release"
